[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run start"
  targetPort = 8888
  framework = "#custom"

[[plugins]]
  package = "./node_modules/@netlify/demo-restaurant-sites-data/plugins/contentful"

  [plugins.inputs]
    # Directory for the generated JSON data files to reside in
    dataDir = "data"